version: '3.8'

services:
  excel-addin:
    image: ${DOCKER_USERNAME:-your-username}/excel-custom-addin:${VERSION:-latest}
    container_name: excel-custom-addin-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - addin-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  addin-network:
    driver: bridge
